import { ChildProcess, spawn } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { HASS_BIN, REPO_ROOT } from './env.js';
import { LogProblem, describeLogProblems, findLogProblems } from './logScan.js';
import { tail, waitFor } from './waitFor.js';

/**
 * Topic prefix the mirror automation publishes entity states under, so a
 * scenario can observe Home Assistant over MQTT instead of authenticating
 * against its HTTP API. One less moving part, and it uses the transport the
 * integration is about anyway.
 */
export const STATE_MIRROR_PREFIX = 'e2e/state';

/**
 * Config entry storage schema version. Home Assistant rewrites the file on
 * start; a mismatch surfaces as "config entry not loaded" rather than silent
 * misbehaviour. Bump alongside the pinned version in versions.json.
 */
const CONFIG_ENTRY_STORAGE_MINOR_VERSION = 5;
const MQTT_ENTRY_ID = 'hm2mqtte2ehm2mqtte2ehm2mqtte2e01';

export interface HomeAssistantOptions {
  /** Directory to generate the configuration in; wiped first. */
  configDir: string;
  brokerPort: number;
  discoveryPrefix?: string;
  /**
   * Entity id substring whose state changes are mirrored to MQTT. Restricting
   * it keeps the mirror away from its own automation entity, which would
   * otherwise retrigger itself forever.
   */
  mirrorEntitiesMatching?: string;
}

export interface HomeAssistant {
  readonly configDir: string;
  log(): string;
  /** Lines the scan considers a complaint about hm2mqtt. */
  problems(allowlist?: RegExp[]): LogProblem[];
  assertNoProblems(allowlist?: RegExp[]): void;
  stop(): Promise<void>;
}

function configurationYaml(
  options: Required<Pick<HomeAssistantOptions, 'mirrorEntitiesMatching'>>,
) {
  return `# Generated by the hm2mqtt e2e harness. Do not edit.
homeassistant:
  name: hm2mqtt e2e
  latitude: 0
  longitude: 0
  elevation: 0
  unit_system: metric
  time_zone: UTC
logger:
  default: info
automation:
  # Mirrors entity states to MQTT so the scenario can read them without
  # authenticating against the HTTP API. Queued, because dropping overlapping
  # runs would log a warning of its own.
  - alias: e2e state mirror
    mode: queued
    max: 1000
    triggers:
      - trigger: event
        event_type: state_changed
    conditions:
      - condition: template
        value_template: >-
          {{ '${options.mirrorEntitiesMatching}' in trigger.event.data.entity_id }}
    actions:
      - action: mqtt.publish
        data:
          topic: "${STATE_MIRROR_PREFIX}/{{ trigger.event.data.entity_id }}"
          retain: true
          payload: >-
            {{ trigger.event.data.new_state.state if trigger.event.data.new_state else 'removed' }}
`;
}

function configEntriesJson(brokerPort: number, discoveryPrefix: string) {
  return JSON.stringify(
    {
      version: 1,
      minor_version: CONFIG_ENTRY_STORAGE_MINOR_VERSION,
      key: 'core.config_entries',
      data: {
        entries: [
          {
            created_at: '2020-01-01T00:00:00+00:00',
            modified_at: '2020-01-01T00:00:00+00:00',
            data: {
              broker: '127.0.0.1',
              port: brokerPort,
              discovery: true,
              discovery_prefix: discoveryPrefix,
            },
            disabled_by: null,
            discovery_keys: {},
            domain: 'mqtt',
            entry_id: MQTT_ENTRY_ID,
            minor_version: 2,
            options: {},
            pref_disable_new_entities: false,
            pref_disable_polling: false,
            source: 'user',
            subentries: [],
            title: 'e2e broker',
            unique_id: null,
            version: 1,
          },
        ],
      },
    },
    null,
    2,
  );
}

export function writeHomeAssistantConfig(options: HomeAssistantOptions): void {
  const { configDir, brokerPort } = options;
  rmSync(configDir, { recursive: true, force: true });
  mkdirSync(join(configDir, '.storage'), { recursive: true });
  writeFileSync(
    join(configDir, 'configuration.yaml'),
    configurationYaml({ mirrorEntitiesMatching: options.mirrorEntitiesMatching ?? 'hame_energy' }),
  );
  writeFileSync(
    join(configDir, '.storage/core.config_entries'),
    configEntriesJson(brokerPort, options.discoveryPrefix ?? 'homeassistant'),
  );
}

/**
 * Start Home Assistant against the scenario's broker.
 *
 * Readiness is the log line Home Assistant prints when its bootstrap is done;
 * the MQTT connection is confirmed separately by the caller, which can see the
 * broker accept the client.
 */
export async function startHomeAssistant(options: HomeAssistantOptions): Promise<HomeAssistant> {
  writeHomeAssistantConfig(options);
  const logFile = join(options.configDir, 'home-assistant.log');

  const child: ChildProcess = spawn(
    HASS_BIN,
    ['-c', options.configDir, '--skip-pip', '--log-file', logFile, '--log-no-color'],
    { cwd: REPO_ROOT, stdio: ['ignore', 'pipe', 'pipe'] },
  );
  let consoleOutput = '';
  child.stdout?.on('data', chunk => (consoleOutput += chunk.toString()));
  child.stderr?.on('data', chunk => (consoleOutput += chunk.toString()));
  let exited = false;
  child.on('exit', () => (exited = true));

  const readLog = () => {
    try {
      return readFileSync(logFile, 'utf8');
    } catch {
      return '';
    }
  };

  await waitFor(
    'Home Assistant to finish starting',
    () => {
      if (exited) {
        throw new Error(`Home Assistant exited early:\n${tail(consoleOutput)}`);
      }
      return /Home Assistant initialized/.test(readLog());
    },
    { timeoutMs: 180_000, diagnose: () => `Home Assistant log:\n${tail(readLog())}` },
  );

  // A config entry that failed to load produces no entities at all, which would
  // otherwise show up much later as an unexplained timeout.
  const entryFailure = /Error setting up entry .* for mqtt/.exec(readLog());
  if (entryFailure) {
    throw new Error(
      `Home Assistant could not set up the MQTT integration:\n${tail(readLog(), 30)}`,
    );
  }

  const homeAssistant: HomeAssistant = {
    configDir: options.configDir,
    log: readLog,
    problems: (allowlist = []) => findLogProblems(readLog(), allowlist),
    assertNoProblems(allowlist = []) {
      const problems = this.problems(allowlist);
      if (problems.length > 0) {
        throw new Error(
          `Home Assistant logged ${problems.length} problem(s) about hm2mqtt:\n` +
            describeLogProblems(problems),
        );
      }
    },
    async stop() {
      if (exited) {
        return;
      }
      child.kill('SIGTERM');
      await waitFor('Home Assistant to exit', () => exited, {
        timeoutMs: 60_000,
        diagnose: () => `Home Assistant log:\n${tail(readLog())}`,
      }).catch(() => child.kill('SIGKILL'));
    },
  };
  return homeAssistant;
}
