---
name: Bug report
description: Report a problem with hm2mqtt
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue. Please provide the device details below.
  - type: input
    id: device_model
    attributes:
      label: Device Model
      description: |
        Supported models: B2500 HMA/HMB/HMJ, Marstek Venus C, Marstek Venus E, Marstek Jupiter C, Marstek Jupiter E, Marstek Jupiter Plus
    validations:
      required: true
  - type: input
    id: firmware_version
    attributes:
      label: Firmware Version
    validations:
      required: true
  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: Provide a clear and concise description of the problem.
    validations:
      required: true
