---
name: Feature request
description: Suggest an idea for hm2mqtt
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please provide details below.
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Describe the feature or improvement you would like to see.
    validations:
      required: true
  - type: input
    id: device_model
    attributes:
      label: Device Model (optional)
      description: |
        Supported models: B2500 HMA/HMB/HMJ, Marstek Venus C, Marstek Venus E, Marstek Jupiter C, Marstek Jupiter E, Marstek Jupiter Plus, Marstek CT002 Smart Meter
    validations:
      required: false
  - type: input
    id: firmware_version
    attributes:
      label: Firmware Version (optional)
    validations:
      required: false
