---
name: Question
description: Ask a question about hm2mqtt
labels: question
body:
  - type: markdown
    attributes:
      value: |
        If you have a question about using hm2mqtt, please ask below.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Describe your question in detail.
    validations:
      required: true
  - type: input
    id: device_model
    attributes:
      label: Device Model (optional)
      description: |
        Supported models: B2500 HMA/HMB/HMJ, Marstek Venus C, Marstek Venus E, Marstek Jupiter C, Marstek Jupiter E, Marstek Jupiter Plus, Marstek CT002 Smart Meter
    validations:
      required: false
  - type: input
    id: firmware_version
    attributes:
      label: Firmware Version (optional)
    validations:
      required: false
