name: Release

run-name: Release v${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.5.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run release script
        run: ./release.sh ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          body: |
            Release v${{ github.event.inputs.version }}
            
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/${{ github.event.inputs.version }}/CHANGELOG.md) for detailed changes.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "🎉 Release v${VERSION} completed successfully!"
          echo ""
          echo "📋 Summary:"
          echo "- Release branch: release/v${VERSION} (kept for potential hotfixes)"
          echo "- Main branch: Updated to v${VERSION}"
          echo "- Tag: ${VERSION} created"
          echo "- GitHub Release: Created"
          echo "- Develop branch: Ready for next development cycle"
          echo ""
          echo "🔗 Links:"
          echo "- Release: https://github.com/${{ github.repository }}/releases/tag/${VERSION}"
          echo "- Release branch: https://github.com/${{ github.repository }}/tree/release/v${VERSION}"
